### ISSUE TITLE
Consistent test names

### ISSUE THREAD

**Issue by gabrieldemian** [gabrieldemian/vincenzo#7]
The test names are not consistent, some tests are using "should_", and others are not. Some tests could have more descriptive names, and maybe more comments, where applicable, to help to understand what the test is supposed to do.

**Comment by conelul** [comment]
I'll give this a shot. I'm a bit new to PRs and whatnot but I have a decent amount of Rust experience.

**Comment by gabrieldemian** [comment]
> I'll give this a shot. I'm a bit new to PRs and whatnot but I have a decent amount of Rust experience.

Sounds great, thanks in advance! PRs are easy to work with, you just create a new branch, push your changes, and then you use github to make the PR.
